<?php

define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_PLUGINNAME', 'Stop Automatically Saving Draft');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_DESCIRPTION', 'ドラフトの自動保存機能を停止します。');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_OPTION_ACTIVE', '自動保存を停止しますか?');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_OPTION_ACTIVE_YES', '停止する');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_OPTION_ACTIVE_NO', '停止しない');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_OPTION_ACTIVE_GLOBAL', '全体の設定に従う');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_FORMAT_DESC', ' (現在の設定は「%s」です)');
define('PLUG_STOPAUTOSAVINGDRAFT_TEXT_OPTION_MEMBERSETTING', 'メンバーごとの設定を許可する');

?>